Add System variable replacement
mbbsemu/MBBSEmu pull request #392
Opened 2021-01-30 23:49 UTC by tuday2

-Tested adding a variable called DATE with BBSDRAW.EXE (MajorBBS ANSI program)

2021-01-31 00:44 UTC, tuday2 commented
-Still need to add justification detection and padding (first two characters and last 2 numbers), sample below
R4TEXT_VAR_RJUS20
C9TEXT_VAR_CJ_25
N.TEXT_VAR_NOJUS

2021-02-06 14:23 UTC, enusbaum requested changes

2021-02-06 14:23 UTC, enusbaum commented on MBBSEmu/Session/SessionBase.cs
> +                var sessionVariables = new Dictionary<string, string>
Can we set this in the SessionBase constructor so we're not newing it up with every output?

2021-02-06 14:23 UTC, enusbaum commented on MBBSEmu/TextVariables/TextVariableService.cs
> +                var variableText = GetVariableByName($"{variableName}");
I don't think we need the string formatter here, can just pass in `variableName`

2021-02-07 01:22 UTC, enusbaum approved these changes

2021-02-07 01:23 UTC, merged