Add check for module = enabled in rlogin by port
mbbsemu/MBBSEmu pull request #453
Opened 2021-03-28 12:39 UTC by tuday2

Closes #451

2021-03-29 00:07 UTC, enusbaum requested changes
Need to add && Module.Enabled or `.Where(x=> x.ModuleConfig.Enabled)` checks in MbbsHost on:

`ProcessRTKICK()`
`ProcessRTIHDLR()`
`ProcessSYSCYC()`
`ProcessTasks()`
`CallModuleRoutine`

To ensure we're only invoking these methods on modules that are enabled.

2021-04-02 23:51 UTC, tuday2 commented on MBBSEmu/HostProcess/MbbsHost.cs
> +            if (!module.ModuleConfig.ModuleEnabled)
Yes, this way simplifies enable/disable -- really we are just turning off the main program loop for the module and hiding from menu -- tested and this works great.

2021-04-02 23:52 UTC, tuday2 commented on MBBSEmu/Module/MBBSModule.cs
> +            if (!moduleConfig.ModuleEnabled)
Removed in new simpler enable/disable

2021-04-03 14:05 UTC, enusbaum approved these changes

2021-04-03 14:05 UTC, merged