Add opcodes - Js, Jns, Fldpi, Fxch, Fpatan, Fscale
mbbsemu/MBBSEmu pull request #462
Opened 2021-04-04 18:15 UTC by tuday2

Draft -- need some assistance

2021-04-04 19:51 UTC, paladine commented on MBBSEmu/CPU/CPUCore.cs
> +            (ST0, ST1) = (ST1, ST0);
doesn't this just change the local variable values and not the values actually in the FpuStack?

2021-04-11 12:38 UTC, enusbaum requested changes
Only the three small changes and it looks good to me!

2021-04-11 12:38 UTC, enusbaum commented on MBBSEmu.Tests/CPU/JS_JNS_Tests.cs
> +                mbbsEmuCpuRegisters.F = mbbsEmuCpuRegisters.F.SetFlag((ushort)EnumFlags.SF);
You can now use `mbbsEmuCpuRegisters.SignFlag = signFlagValue;`

2021-04-11 12:38 UTC, enusbaum commented on MBBSEmu.Tests/CPU/JS_JNS_Tests.cs
> +                mbbsEmuCpuRegisters.F = mbbsEmuCpuRegisters.F.SetFlag((ushort)EnumFlags.SF);
See Above

2021-04-11 12:38 UTC, enusbaum commented on MBBSEmu.Tests/CPU/FXCH_Tests.cs
> +            instructions.fxch(st0, st1);
I would add another test that might switch `ST0` and `ST4` as well

2021-04-11 13:13 UTC, tuday2 commented on MBBSEmu/CPU/CPUCore.cs
> +            var source = GetOperandValueDouble(_currentInstruction.Op0Kind, EnumOperandType.Source);
Per our convo source/destination covers this and proved by test

2021-04-11 13:32 UTC, enusbaum approved these changes

2021-04-11 13:37 UTC, merged