Add gender support
mbbsemu/MBBSEmu pull request #493
Opened 2021-06-06 11:26 UTC by tuday2

Closes #480

2021-06-06 22:59 UTC, tuday2 commented
Ready for first review

2021-06-09 12:17 UTC, enusbaum requested changes

2021-06-09 12:17 UTC, enusbaum commented on MBBSEmu/Program.cs
> +            _accountBtrieve.Insert(new UserAccount { userid = Encoding.ASCII.GetBytes("sysop"), psword = Encoding.ASCII.GetBytes("<<HASHED>>"), sex = 77 }.Data, LogLevel.Error);
probably do `(byte)'M'` here so it's easier to read

2021-06-09 12:17 UTC, enusbaum commented on MBBSEmu/HostProcess/GlobalRoutines/SysopGlobal.cs
> +            accountGender = accountGender == 70 ? (byte) 77 : (byte) 70;
`(byte)'M'` and `(byte)'F'` here so it's easier to read

2021-06-09 13:43 UTC, merged